### ISSUE TITLE
Hacer la función fakeUnion

### ISSUE THREAD

**Issue by erickaldiaz** [erickaldiaz/fakeMDN#42]
Implementar el método fakeUnion  que compara 2 arrays y retorna un nuevo array con la unión de los valores de ambos, sin repeticiones. Preservar el orden de los elementos, comenzando desde el primer elemento del primer array pasado por parámetro. [referencia](https://lodash.com/docs/4.17.11#union)

**Comment by livchits** [comment]
#48 Completada
