### ISSUE TITLE
Cosas a arreglar para la parte 4

### ISSUE THREAD

**Issue by nhsz** [erickaldiaz/fakeMDN#82]
- [x] `fakeEvery` debería cortar en el primer test que de `false`, no hace falta iterar todos en ese caso 
- [x] En `fakeIndexOfRecursive`, sacar la función auxiliar afuera
- [x] En `fakeIndexOf`, (iterativo), agregarle el `let` al índice (para que no sea global) y usar `===`en las comparaciones, para evitar coercion
- [x] En el `fakeReduce`, usar alguna variable para el índice que se usa para iterar, para evitar repetir código

**Comment by livchits** [comment]
Corregidas. El cambio en fakeReduce aún está en su rama.
