### ISSUE TITLE
Sugerencias para el template

### ISSUE THREAD

**Issue by livchits** [erickaldiaz/fakeMDN#93]
Lo que vi que me parece que se puede "corregir" del template son estas cosas:

1. Los width del body, el header y el footer al 100% no son necesarios. Capaz esto tiene que ver con que le haya puesto flexbox al body 🤔 
2. En el main el width lo bajaría a 70% y en el query `@media only screen and (min-width: 750px)` lo pasaría a 90%.
3. También se puede sacar el width de .sidebar-item del 100%.
4. En la clase navbar cambiaría el width: 100% por un flex: 1.
5. En el html, habría que sacar la section con class head fuera del main 
``` 
<section class="head">
    <h1>Javascript</h1>
</section>
```
6. Sacaría los dos estilos que tiene la clase sidebar, para que el sidebar y el texto principal no se superpongan en pantallas más angostas:
```
.sidebar {
 width: 23%;
 margin-right: 0.2em;
}
```

Y se me ocurren un par de cambios que son opinables:

1. En la clase head bajarle el width a 70% y cambiarle el padding para que quede así:
```
.head {
  width: 70%;
  border-bottom: 5px solid;
  border-image-source: linear-gradient(5deg, var(--secondary-color), var(--white));
  border-image-slice: 1;
  margin: auto;
  padding: 1em 1em;
}
```
2. Cambiaría el padding de los a en sidebar-item para que quede así:
```
.sidebar-item > a {
  display: block;
  padding: 0 0.5em;
  line-height: 2em;
}
```
3. En el query `@media (max-width: 750px)` el width de .sidebar lo bajaría a 66%. Y, para que no queden espacios locos, modificaría los márgenes de las siguientes clases y objetos así (idealmente hay que consultar si meter flexbox al body para eliminar el espacio en blanco de abajo fue una buena idea):
```
.head {
  margin: 0;
}
main {
 margin: 0 auto;
}
```

**Comment by mborroni** [comment]
Al final Nico dijo que el título tenía que ir dentro del main porque era contenido que no se repetía
